<a href="https://colab.research.google.com/github/Amir-mjafari/classification_Oxford_102_flowers/blob/main/fellow_ai_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
# UnZIP files
# file name: oxford-102-flowers.zip

!unzip gdrive/My\ Drive/oxford-102-flowers.zip > /flowers

# from so on, we use flowers directory to acces the data

In [ ]:
# loading paths and labels

import pandas as pd

train_data = pd.read_csv('oxford-102-flowers/train.txt', header = None, delimiter = "\s+", index_col = False )
train_data.columns = ["path", "label"]

valid_data = pd.read_csv('oxford-102-flowers/valid.txt', header = None, delimiter = "\s+", index_col = False )
valid_data.columns = ["path", "label"]

test_data = pd.read_csv('oxford-102-flowers/test.txt', header = None, delimiter = "\s+", index_col = False )
test_data.columns = ["path", "label"]

print(train_data)
print(valid_data)
print(test_data)


                     path  label
0     jpg/image_03860.jpg     16
1     jpg/image_06092.jpg     13
2     jpg/image_02400.jpg     42
3     jpg/image_02852.jpg     55
4     jpg/image_07710.jpg     96
...                   ...    ...
1015  jpg/image_02944.jpg     59
1016  jpg/image_07434.jpg     93
1017  jpg/image_02684.jpg     57
1018  jpg/image_01639.jpg     81
1019  jpg/image_03165.jpg     10

[1020 rows x 2 columns]
                     path  label
0     jpg/image_04467.jpg     89
1     jpg/image_07129.jpg     44
2     jpg/image_05166.jpg      4
3     jpg/image_07002.jpg     34
4     jpg/image_02007.jpg     79
...                   ...    ...
1015  jpg/image_08182.jpg     61
1016  jpg/image_07029.jpg     38
1017  jpg/image_05956.jpg     67
1018  jpg/image_06051.jpg     13
1019  jpg/image_07724.jpg     96

[1020 rows x 2 columns]
                     path  label
0     jpg/image_06977.jpg     34
1     jpg/image_00800.jpg     80
2     jpg/image_05038.jpg     58
3     jpg/image_06759.jpg 

In [ ]:
# loading TRAIN/TEST/VALID images + TRAIN/TEST/VALID labels

import cv2
import numpy as np

def load_data(x):

  #x is a DataFrame passed into the function

  datasets = 'oxford-102-flowers'
      
  images = []
      
  for img_path in x['path']:
          
      IMAGE_SIZE = (224,224)


      image_path = datasets +'/' + str(img_path)

      image = cv2.imread(image_path)
      # image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # Test!
      image = cv2.resize(image, IMAGE_SIZE) 

      images.append(image)
          
  images = np.array(images, dtype = 'float32')
  labels = np.array(x['label'], dtype = 'int32')

  return images, labels

In [ ]:
# loading data with load_data() function by passing in the 
# test/train/valid DataFrames including 'path' and 'label'

train_images, train_labels = load_data(train_data)
valid_images, valid_labels = load_data(valid_data)
test_images, test_labels = load_data(test_data)
# print(test_images)

In [ ]:
print(train_images)
print(test_labels.shape)

[[[[ 24.  74.  76.]
   [ 22.  72.  74.]
   [ 27.  76.  78.]
   ...
   [ 57. 102.  99.]
   [ 57. 102.  99.]
   [ 57. 102.  99.]]

  [[ 27.  78.  80.]
   [ 25.  76.  78.]
   [ 28.  77.  79.]
   ...
   [ 58. 103. 100.]
   [ 58. 103. 100.]
   [ 57. 102.  99.]]

  [[ 27.  78.  80.]
   [ 27.  78.  80.]
   [ 25.  74.  76.]
   ...
   [ 57. 104. 101.]
   [ 57. 104. 101.]
   [ 55. 102.  99.]]

  ...

  [[ 79.  94. 110.]
   [ 77.  92. 108.]
   [ 75.  90. 106.]
   ...
   [104. 117. 133.]
   [ 99. 112. 128.]
   [ 97. 110. 126.]]

  [[ 78.  93. 110.]
   [ 77.  93. 108.]
   [ 75.  92. 108.]
   ...
   [101. 115. 133.]
   [ 97. 111. 129.]
   [ 95. 109. 127.]]

  [[ 72.  89. 104.]
   [ 72.  87. 104.]
   [ 71.  87. 103.]
   ...
   [101. 115. 133.]
   [ 97. 111. 129.]
   [ 95. 109. 127.]]]


 [[[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]
   ...
   [  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]
   ...
   [  0.   0.   0.]
 

In [ ]:
import tensorflow.keras as K
import math
import os
import matplotlib.pyplot as plt

num_of_class = len(np.unique(test_labels))
def prep_data(x, y):

    # x: Numpy array of images (n, 224, 224, 3) 
    # y: Numpy array of labels  


    x_p = K.applications.resnet50.preprocess_input(x)
    y_p = K.utils.to_categorical(y, num_of_class)

    return x_p, y_p

In [ ]:
prep_train_images, prep_train_labels = prep_data(train_images, train_labels)
prep_valid_images, prep_valid_labels = prep_data(valid_images, valid_labels)
prep_test_images, prep_test_labels = prep_data(test_images, test_labels)

In [ ]:
print(prep_train_images)

[[[[-2.7939003e+01 -4.2778999e+01 -9.9680000e+01]
   [-2.9939003e+01 -4.4778999e+01 -1.0168000e+02]
   [-2.5939003e+01 -4.0778999e+01 -9.6680000e+01]
   ...
   [-4.9390030e+00 -1.4778999e+01 -6.6680000e+01]
   [-4.9390030e+00 -1.4778999e+01 -6.6680000e+01]
   [-4.9390030e+00 -1.4778999e+01 -6.6680000e+01]]

  [[-2.3939003e+01 -3.8778999e+01 -9.6680000e+01]
   [-2.5939003e+01 -4.0778999e+01 -9.8680000e+01]
   [-2.4939003e+01 -3.9778999e+01 -9.5680000e+01]
   ...
   [-3.9390030e+00 -1.3778999e+01 -6.5680000e+01]
   [-3.9390030e+00 -1.3778999e+01 -6.5680000e+01]
   [-4.9390030e+00 -1.4778999e+01 -6.6680000e+01]]

  [[-2.3939003e+01 -3.8778999e+01 -9.6680000e+01]
   [-2.3939003e+01 -3.8778999e+01 -9.6680000e+01]
   [-2.7939003e+01 -4.2778999e+01 -9.8680000e+01]
   ...
   [-2.9390030e+00 -1.2778999e+01 -6.6680000e+01]
   [-2.9390030e+00 -1.2778999e+01 -6.6680000e+01]
   [-4.9390030e+00 -1.4778999e+01 -6.8680000e+01]]

  ...

  [[ 6.0609970e+00 -2.2778999e+01 -4.4680000e+01]
   [ 4.0609970e+

In [ ]:
# Define a convolutional neural network + ResNet50 pretrained implication

def create_model(freez_layers):

    num_of_class = len(np.unique(test_labels))
    f = freez_layers
    dimension = prep_train_images.shape[1:]
    input_t = K.Input(shape = dimension)
    res_model = K.applications.ResNet50(include_top=False, 
                                        weights='imagenet',
                                        input_tensor=input_t)
    
    # freezing the first 'freez_level' of the ResNet50

    for layer in res_model.layers[:f]:
        layer.trainable = False
    
    for i, layer in enumerate(res_model.layers):
        print(i, layer.name, "-", layer.trainable)

    model = K.models.Sequential()
    model.add(res_model)
    model.add(K.layers.Flatten())
    model.add(K.layers.BatchNormalization())
    model.add(K.layers.Dense(256, activation='relu'))
    model.add(K.layers.Dropout(0))
    model.add(K.layers.BatchNormalization())
    model.add(K.layers.Dense(128, activation='relu'))
    model.add(K.layers.Dropout(0))
    model.add(K.layers.BatchNormalization())
    model.add(K.layers.Dense(64, activation='relu'))
    model.add(K.layers.Dropout(0))
    model.add(K.layers.BatchNormalization())
    model.add(K.layers.Dense(num_of_class, activation='softmax'))


    return model   

In [ ]:
def train(model, epochs, data_augmentation, opt):

  

    # Compile the model before using it
    model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
    print(model.summary())

    # create a callback that will save the best model while training
    save_best_model = K.callbacks.ModelCheckpoint('best_model.h5', monitor='val_accuracy', mode='max', save_best_only=True, verbose=0)

    # train without data augmentation
    if not data_augmentation:
        print('Not using data augmentation.')
        history = model.fit(prep_train_images, prep_train_labels,
                            batch_size=batch_size,
                            epochs=epochs,
                            validation_data=(prep_valid_images, prep_valid_labels),
                            shuffle=True,
                            callbacks=[save_best_model],
                            verbose=1)

    # train with data augmentation
    else:
        print('Using real-time data augmentation.')
        # This will do preprocessing and realtime data augmentation:
        datagen = K.preprocessing.image.ImageDataGenerator(
            featurewise_center=False,  # set input mean to 0 over the dataset
            samplewise_center=False,  # set each sample mean to 0
            featurewise_std_normalization=False,  # divide inputs by std of the dataset
            samplewise_std_normalization=False,  # divide each input by its std
            zca_whitening=False,  # apply ZCA whitening
            zca_epsilon=1e-06,  # epsilon for ZCA whitening
            rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
            # randomly shift images horizontally (fraction of total width)
            width_shift_range=0.1,
            # randomly shift images vertically (fraction of total height)
            height_shift_range=0.1,
            shear_range=0.,  # set range for random shear
            zoom_range=0.,  # set range for random zoom
            channel_shift_range=0.,  # set range for random channel shifts
            # set mode for filling points outside the input boundaries
            fill_mode='nearest',
            cval=0.,  # value used for fill_mode = "constant"
            horizontal_flip=True,  # randomly flip images
            vertical_flip=False,  # randomly flip images
            # set rescaling factor (applied before any other transformation)
            rescale=None,
            # set function that will be applied on each input
            preprocessing_function=None,
            # image data format, either "channels_first" or "channels_last"
            data_format=None,
            # fraction of images reserved for validation (strictly between 0 and 1)
            validation_split=0.0)

        # Compute quantities required for feature-wise normalization
        # (std, mean, and principal components if ZCA whitening is applied).
        datagen.fit(prep_train_images)

        # Fit the model on the batches generated by datagen.flow().
        history = model.fit(datagen.flow(prep_train_images, prep_train_labels, batch_size=batch_size),
                            steps_per_epoch=math.ceil(prep_train_images.shape[0]/batch_size),
                            epochs=epochs,
                            validation_data=(prep_valid_images, prep_valid_labels),
                            callbacks=[save_best_model],
                            verbose=1)
    
    return history

In [ ]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 5314465485268091404
xla_global_id: -1
]


In [ ]:
# configuration

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import keras
from keras.models import Sequential, load_model
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.callbacks import ModelCheckpoint
from keras.preprocessing.image import ImageDataGenerator
import math
import os
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import seaborn as sn; sn.set(font_scale=1.4)
from sklearn.utils import shuffle           
import matplotlib.pyplot as plt             
import cv2                                 
import tensorflow as tf                
from tqdm import tqdm

batch_size = 32
optimizer = K.optimizers.Adam()
num_classes = len(np.unique(test_labels))
freez_layers = 81

# creating the CNN + Resnet50 model
model = create_model(freez_layers)
model.summary()

# training phase
history = train(model, epochs=60, data_augmentation= True , opt=optimizer,)
saved_model = load_model('best_model.h5')
#scores = saved_model.evaluate(x_test, y_test, verbose=1)

# Plot training accuracy
plt.plot(history.history['accuracy'])
plt.title('training accuracy')
plt.ylabel('training accuracy')
plt.xlabel('epoch')
plt.legend(['Conv'], loc='upper left')
plt.show()

# Plot validation accuracy
plt.plot(history.history['val_accuracy'])
plt.title('validation accuracy')
plt.ylabel('validation accuracy')
plt.xlabel('epoch')
plt.legend(['Conv'], loc='upper left')
plt.show()

94781440/94765736 [==============================] - 1s 0us/step
0 input_1 - False
1 conv1_pad - False
2 conv1_conv - False
3 conv1_bn - False
4 conv1_relu - False
5 pool1_pad - False
6 pool1_pool - False
7 conv2_block1_1_conv - False
8 conv2_block1_1_bn - False
9 conv2_block1_1_relu - False
10 conv2_block1_2_conv - False
11 conv2_block1_2_bn - False
12 conv2_block1_2_relu - False
13 conv2_block1_0_conv - False
14 conv2_block1_3_conv - False
15 conv2_block1_0_bn - False
16 conv2_block1_3_bn - False
17 conv2_block1_add - False
18 conv2_block1_out - False
19 conv2_block2_1_conv - False
20 conv2_block2_1_bn - False
21 conv2_block2_1_relu - False
22 conv2_block2_2_conv - False
23 conv2_block2_2_bn - False
24 conv2_block2_2_relu - False
25 conv2_block2_3_conv - False
26 conv2_block2_3_bn - False
27 conv2_block2_add - False
28 conv2_block2_out - False
29 conv2_block3_1_conv - False
30 conv2_block3_1_bn - False
31 conv2_block3_1_relu - False
32 conv2_block3_2_conv - False
33 conv2_block3_2_bn

/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  layer_config = serialize_layer_fn(layer)


32/32 [==============================] - 500s 16s/step - loss: 4.4459 - accuracy: 0.0529 - val_loss: 119.2031 - val_accuracy: 0.0088
Epoch 2/60
32/32 [==============================] - 492s 16s/step - loss: 3.5504 - accuracy: 0.2275 - val_loss: 921.5319 - val_accuracy: 0.0088
Epoch 3/60
32/32 [==============================] - 494s 16s/step - loss: 2.8431 - accuracy: 0.4480 - val_loss: 25.1181 - val_accuracy: 0.0392
Epoch 4/60
32/32 [==============================] - 497s 16s/step - loss: 2.2971 - accuracy: 0.6010 - val_loss: 998.2975 - val_accuracy: 0.0167
Epoch 5/60
32/32 [==============================] - 495s 16s/step - loss: 1.7825 - accuracy: 0.7265 - val_loss: 455.3291 - val_accuracy: 0.0137
Epoch 6/60
32/32 [==============================] - 502s 16s/step - loss: 1.4487 - accuracy: 0.7745 - val_loss: 7.6273 - val_accuracy: 0.2225
Epoch 7/60
32/32 [==============================] - 498s 16s/step - loss: 1.2344 - accuracy: 0.8118 - val_loss: 34.7173 - val_accuracy: 0.1853
Epoch 8